version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: doctor-management-laravel
    container_name: doctor-management-laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
    networks:
      - doctor-management

networks:
  doctor-management:
    driver: bridge
